# Generated by Django 5.1.1 on 2024-09-25 05:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 26, 5, 33, 18, 600880, tzinfo=datetime.timezone.utc)),
        ),
    ]
