# Generated by Django 5.1.1 on 2024-09-25 12:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0004_alter_tokenproxy_options'),
        ('product', '0004_alter_token_expiry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_date', models.DateTimeField(default=datetime.datetime(2024, 9, 26, 12, 6, 58, 128505, tzinfo=datetime.timezone.utc))),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extension', to='authtoken.token')),
            ],
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
