# Generated by Django 5.1.1 on 2024-09-27 08:28

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_tokenextension_delete_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tokenextension',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 28, 8, 28, 21, 596661, tzinfo=datetime.timezone.utc)),
        ),
    ]
